name: shelf_letsencrypt
description: Let's Encrypt support for the shelf package (free and automatic HTTPS certificate support).
version: 1.1.1
homepage: https://github.com/gmpassos/shelf_letsencrypt

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  path: ^1.8.3
  shelf: ^1.4.0
  acme_client: ^1.1.0
  basic_utils: ^3.9.4
  coverage: ^1.6.3
  collection: ^1.16.0

dependency_overrides:
  acme_client:
    git:
      url: https://github.com/NiKoTron/Dart-Acme-Client.git
      ref: dependencies-update

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  dependency_validator: ^3.2.2
