name: shelf_letsencrypt
description: Let's Encrypt support for the shelf package (free and automatic HTTPS certificate support).
version: 1.0.1
homepage: https://github.com/gmpassos/shelf_letsencrypt

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  path: ^1.8.0
  shelf: ^1.2.0
  acme_client: ^1.0.1
  basic_utils: ^3.7.0
  coverage: ^1.0.3
  dependency_validator: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
